(ns recruit-app.terms-of-use.views
  (:require [re-frame.core :as rf]
            [re-com.core :as rc
             :refer-macros [handler-fn]]
            [reagent.core :as reagent]
            [re-com.util :refer [enumerate]]
            [cljs.reader :refer [read-string]]
            [reagent.core :as r]
            [domina.events :as events]
            [goog.string :as gstring]))


(defn title
  []
  (fn []
    [rc/h-box
     :class "header-h1"
     :children [
                [:h1 {:class "title" :id "top"} "Recruiter User Agreement"]]]))

(defn paras
  []
  (fn []
    [rc/v-box
     :class "terms"
     :children [
                [:p "Last Updated 08/28/2017"]
                [:p "THE TERMS AND CONDITIONS SET FORTH HEREIN (\"THE TERMS\") ARE A LEGAL CONTRACT BETWEEN YOU AND LADDERS, INC. (\"LADDERS\", \"WE\" OR \"US\"). THE TERMS EXPLAIN HOW YOU ARE PERMITTED TO USE THE WEBSITE LOCATED AT "
                 [:a {:href "https://recruit.theladders.com" :target "_blank"} "RECRUIT.THELADDERS.COM"]
                 " AS WELL AS ALL ASSOCIATED SITES LINKED TO "
                 [:a {:href "https://recruit.theladders.com" :target "_blank"} "RECRUIT.THELADDERS.COM"]
                 " BY LADDERS, ITS SUBSIDIARIES AND AFFLILIATED COMPANIES (COLLECTIVELY, THE \"SITE\"), AND ALL SOFTWARE, SERVICES, OR CONTENT ASSOCIATED WITH THE SITE (COLLECTIVELY, THE \"SERVICES\"). UNLESS OTHERWISE SPECIFICED, ALL REFERENCES TO \"SITE\" OR \"APP\" INCLUDE THE SERVICES AVAILABLE THROUGH THE SITE. BY USING THIS SITE OR THE SERVICES, YOU ARE AGREEING TO ALL OF THESE TERMS; IF YOU DO NOT AGREE WITH ANY OF THESE TERMS, DO NOT ACCESS OR OTHERWISE USE THE SITE, ANY OF THE SERVICES, OR ANY INFORMATION OR MATERIALS CONTAINED WITHIN THE SITE. IF YOU ARE USING THE SITE FOR YOUR COMPANY'S USE, YOU REPRESENT THAT YOU ARE AN AUTHORIZED REPRESENTATIVE WHO HAS THE AUTHORITY TO LEGALLY BIND YOUR COMPANY TO THESE TERMS."]
                [:p "NOTE: THESE TERMS CONTAIN A DISPUTE RESOLUTION AND ARBITRATION PROVISION, INCLUDING CLASS ACTION WAIVER THAT AFFECTS YOUR RIGHTS UNDER THESE TERMS AND WITH RESPECT TO DISPUTES YOU MAY HAVE WITH LADDERS, UNLESS SPECIFICALLY PROHIBITED BY APPLICABLE CONSUMER PROTECTION LEGISLATION. YOU MAY OPT OUT OF THE BINDING INDIVIDUAL ARBITRATION AND CLASS ACTION WAIVER AS PROVIDED BELOW."]
                [:p "These Terms represent the parties' entire understanding regarding the Services and shall control over any different or additional terms contained within any other document.  Ladders' Services enable employers and professional recruiters to post jobs or opportunities (\"Opportunities\"), search for, identify and reach out to job seekers (\"Member\" or \"Members\") in the employment market for professional positions. The words \"you,\" \"your,\" or \"user\" whether or not capitalized, as used herein, refer to any recruiter or employer and/or entities accessing or using the Site or any Services, for any reason."]
                [:p {:style {:font-family "HelveticaNeue"}} "Changes."]
                [:p "Ladders may, from time to time, make changes to the content and features of the Site and any Services (not including these Terms) at any time, including changing, updating, or adding or removing provisions of these Terms.  If we make a material modification to these "
                 [:a {:href "https://recruit.theladders.com/register/viewTerms" :target "_blank"} "Terms"]
                 " or the "
                 [:a {:href "https://recruit.theladders.com/theladders-privacy" :target "_blank"} "Privacy Policy"]", we will notify you through the email associated with your account. By using the Site and/or the Services after Ladders has updated the Terms or Privacy Policy, you are agreeing to the updated terms; if you do not agree with any of the updated terms, you must stop using the Site and the Services."]
                [:p {:style {:font-family "HelveticaNeue"}} "Eligibility."]
                [:p "Users must be at least the age of majority in the jurisdiction in which you reside in order to use the Site and the Services. By using the Site or the Services, you represent, acknowledge and agree that you are at least the age of majority in the jurisdiction where you reside and have the right, authority and capacity to agree to and abide by these Terms. You also represent that you will use the Site and Services in a manner consistent with any and all applicable laws and regulations. Not all products and services are available in all geographic areas. Your eligibility for particular products and services is subject to final determination by Ladders and/or its affiliates. Ladders may terminate these Terms and your use of the Site and Services without notice if we, in our sole discretion, believe that you are not at least the age of majority in the jurisdiction where you reside, or have otherwise violated the Terms."]
                [:p {:style {:font-family "HelveticaNeue"}} "General Use."]
                [:p "Ladders provides content and Services through the Site that are the copyrighted and/or trademarked work of Ladders or Ladders' third-party licensors and suppliers or other users of the Site (collectively, the \"Materials\"). Materials may include logos, graphics, video, images, software and other content. Subject to the terms and conditions of these Terms, and your compliance with these Terms, Ladders hereby grants you a limited, personal, non-exclusive and non-transferable license to use and to display the Materials and to use the Site and the Services solely for personal or internal business purposes.  Except for the foregoing license, you have no other rights in the Site, the Services or any Materials and you may not modify, edit, copy, reproduce, create derivative works of, reverse engineer, alter, enhance or in any way exploit any of the Site, the Services or the Materials in any manner. If you breach any of these Terms, your account will terminate automatically."]
                [:p {:style {:font-family "HelveticaNeue"}} "Subscriptions."]
                [:p "By registering for an account with Ladders, you will have access to certain password-restricted areas of the Site and certain Services and Materials offered on and through the Site (a \"Subscription\"). The rights and privileges provided to You upon registration are personal and non-transferable."]
                [:p "We offer different Subscription options.  If you have chosen a paid subscription option, the fee that we will charge you for your Subscription will be the price indicated at the point of sale. Ladders reserves the right to change prices for Subscriptions at any time, upon notice, and does not provide price protection or refunds in the event of promotions or price decreases. All sales and payments of Subscription fees will be in US Dollars. You hereby authorize Ladders to charge your credit card or other available payment method associated with your account for any fee indicated at the point of sale. You will be liable for paying any and all applicable sales and use taxes for the purchase of your Subscription.  Fees are non-refundable under any circumstances, subject to applicable laws. Paid Subscriptions are effective on the date of your purchase and continue through the subscription period indicated at point of sale. If You choose to discontinue use of the Site prior to the expiration of a paid subscription period, You will continue to be responsible for the full amount due for the entire subscription period."]
                [:p "Free Subscriptions may be canceled at any time by emailing Recruiter Relations at approvals@theladders.com"]
                [:p "CERTAIN SUBSCRIPTIONS RENEW AUTOMATICALLY.  IF YOU PURCHASE A SUBSCRIPTION THAT AUTOMATICALLY RENEWS, LADDERS WILL AUTOMATICALLY RENEW YOUR SUBSCRIPTION ON THE DAY YOUR CURRENT SUBSCRIPTION PERIOD EXPIRES (THE \"RENEWAL DATE\"), AND LADDERS WILL CHARGE YOU WITH THE APPLICABLE SUBSCRIPTION FEE AND ANY APPLICABLE SALES AND USE TAXES THAT MAY BE IMPOSED ON YOUR SUBSCRIPTION FEE PAYMENT ON THE RENEWAL DATE, UNLESS YOU CANCEL PRIOR TO THE RENEWAL DATE OR UNLESS YOU DISABLE THE AUTO-RENEWAL FUNCTION (SEE BELOW FOR INSTRUCTIONS ON HOW TO DISABLE AUTO-RENEWAL OF SUBSCRIPTIONS)."]
                [:p "Ladders reserves the right to modify pricing at any time (but not the price in effect for your then-current Subscription term), upon advance notice to you.  If you have not cancelled your Subscription or turned off the auto-renew function within the specified time after receiving notice of a price change, your Subscription will auto-renew at the price indicated in your notice.\n        You may choose to turn off the auto-renew function by logging in at the Site and visiting your account page or email rrsupport@theladders.com for assistance."]
                [:p {:style {:font-family "HelveticaNeue"}} "Purchases."]
                [:p "In addition to Subscriptions, we make certain products and services available to users through the Site. You may only order products or services if you are domiciled in the United States or Canada.  You agree to pay all fees corresponding to your order.  You hereby authorize Ladders to charge your credit card or other available payment method associated with your account.  If you do not pay on time or if Ladders cannot charge your credit card or other available payment method for any reason, Ladders reserves the right to either suspend or terminate your access to the Site and account and terminate these Terms. You are expressly agreeing that Ladders is permitted to bill you for the applicable fees, any applicable tax and any other charges you may incur in connection with your use of this Site. If you have a balance due on any account, you agree that Ladders may charge such unpaid fees to your credit card or other available payment method on file or otherwise bill you for such unpaid fees. <strong>All fees paid to Ladders are non-refundable, subject to applicable laws.</strong>"]
                [:p {:style {:font-family "HelveticaNeue"}} "Using the Site, the App and Services."]
                [:p "You may be able to view portions of the Site, without registering with Ladders as a registered user. However, in order to access certain password-restricted areas of the Site and to use certain Services and Materials offered on and through the Site, you must register for an account and receive a password. Once you have submitted your account registration information, Ladders shall have the right to approve or reject the requested registration, in our sole discretion.  Please note that the Services available to you may also vary depending upon your Subscription level."]
                [:p "Ladders may also provide you with the ability to register for an account on the Site using your existing account and log-in credentials through Third-Party Sites (as defined below), which may change from time to time."]
                [:p "You are responsible for maintaining the confidentiality of your Ladders password and any Third Party Site password (collectively, \"Password\"), and you are responsible for all activities that occur using your Password. You agree not to share your Password, let others access or use your Password or do anything else that might jeopardize the security of your Password. You agree to notify Ladders if your Password is lost or stolen, if you are aware of any unauthorized use of your Password on the Site, or if you know of any other breach of security in relation to the Site."]
                [:p "All the information that you provide when registering for an account and otherwise through the Site must be accurate, complete and up to date. You may change, correct or remove certain information from your account by logging into your account at the Site and making the desired changes to your account information."]
                [:p "All Services are provided on a user basis and accounts may be tracked for compliance. If it is determined that unapproved users other than those provided to Ladders are using Services, then Ladders' at its sole discretion may terminate the account upon notice to the user's email address on record or bill You at the then prevailing price for users."]
                [:p "You agree to use the Services in accordance with the terms set forth herein. You understand and agree that the rights granted herein may be used only for the purpose of seeking qualified candidates for available Opportunities. The Site may not be used to mine information from Members, the Site or collect resumes or profile information for unspecified potential future positions. You may not send any communication seeking to solicit any professional services (e.g., executive coaching), nor post any Opportunities on the Site or send out Opportunities for any competitor of Ladders or post or otherwise distribute Opportunities or other content that contains links to any site competitive with Ladders. You are prohibited from using the Site to solicit or promote any home-based business opportunities, fee-based business opportunities or franchise opportunities."]
                [:p "You acknowledge that Ladders collects data and information regarding which job seekers are interested in Opportunities posted by you, and you agree that Ladders may disclose the identity of such job seekers, the fact that those job seekers are interested in your Opportunities, and other data and information regarding those job seekers to other employers and recruiters.  LADDERS DISCLAIMS AND EXCLUDES ANY LIABILITY TO YOU IN CONNECTION WITH SUCH ACTIVITIES."]
                [:p "The Services are subject to storage and usage restrictions (such as limitations on the number of Opportunities you may post, the length of time an Opportunity will remain on the Site, the types of Opportunities permitted to be posted, and the number of resumes you are permitted to view or download), which Ladders may change from time to time."]
                [:p {:style {:font-family "HelveticaNeue"}} "Electronic Communications."]
                [:p "By using the Site and/or the Services, you consent to receiving electronic communications from Ladders. These electronic communications may include information about Ladders' Services and features of the Site, notices about applicable fees and charges, transactional information and other information concerning or related to the Site and/or Services. These electronic communications are part of your relationship with Ladders. You agree that any notices, agreements, disclosures or other communications that we send you electronically will satisfy any legal communication requirements, including that such communications be in writing."]
                [:p {:style {:font-family "HelveticaNeue"}} "Privacy Policy."]
                [:p "Please review Ladders "
                 [:a {:href "http://www.theladders.com/theladders-privacy" :target "_blank"} "Privacy Policy"]
                 ", which is available at "
                 [:a {:href "http://www.theladders.com/theladders-privacy" :target "_blank"} "Privacy Policy"]
                 " (the \"Privacy Policy\") and which explains how we treat the personal information that we collect about you through the Site. You agree that we may treat your personal information in accordance with our "
                 [:a {:href "http://www.theladders.com/theladders-privacy" :target "_blank"} "Privacy Policy"]
                 ", which is incorporated by reference into these Terms."]
                [:p "You agree that you shall not use the personal information of Members except for the purposes of contacting Members about available Opportunities through the Site. You agree that you shall not sell or rent the personal information of Members or other users to third parties for the purpose of marketing products or services of those third parties."]
                [:p {:style {:font-family "HelveticaNeue"}} "Links to Third Party Sites."]
                [:p "The Site may be linked to or may link to third party websites and applications that are not operated by Ladders, including, without limitation, social networking, blogging and similar websites through which you may be able to connect to the Site, and other sites that provide question-and-answer forum functionality or allow you to submit or post information (collectively, \"Third Party Sites\"). Certain areas of the Site may allow you to interact and/or conduct transactions with such Third Party Sites, and, if applicable, allow you to configure your privacy settings in your Third Party Site account to permit your activities on the Site to be shared with your contacts in your Third Party Site account and, in certain situations, you may be transferred to a Third Party Site through a link but it may appear that you are still on our Site. In any case, you acknowledge and agree that the Third Party Sites may have different privacy policies and terms and conditions and/or user guides and business practices than Ladders, and you further acknowledge and agree that your use of such Third Party Sites is governed by the respective Third Party Site privacy policy, terms and conditions, and/or user guides. You hereby agree to comply with any and all terms and conditions, user guides and privacy policies of any of Third Party Sites. Ladders provides links to the Third Party Sites to you as a convenience. Ladders does not verify, make any representations or take responsibility for such Third Party Sites, including, without limitation, the truthfulness, accuracy, quality or completeness of the content, services, links displayed and/or any other activities conducted on or through such Third Party Sites. YOU AGREE THAT LADDERS WILL NOT, UNDER ANY CIRCUMSTANCES, BE RESPONSIBLE OR LIABLE, DIRECTLY OR INDIRECTLY, FOR ANY GOODS, SERVICES, INFORMATION, RESOURCES AND/OR CONTENT AVAILABLE ON OR THROUGH ANY THIRD PARTY SITES AND/OR THIRD-PARTY DEALINGS OR COMMUNICATIONS, OR FOR ANY HARM RELATED THERETO, OR FOR ANY DAMAGES OR LOSS CAUSED OR ALLEGED TO BE CAUSED BY OR IN CONNECTION WITH YOUR USE OR RELIANCE ON THE CONTENT OR BUSINESS PRACTICES OF ANY THIRD PARTY. Any reference on the Site to any product, service, publication, institution, organization of any third party entity or individual does not constitute or imply Ladders' endorsement or recommendation."]
                [:p {:style {:font-family "HelveticaNeue"}} "Third Party Content."]
                [:p "Certain information and other content that are not User Content (defined below) may be provided by third party licensors and suppliers to Ladders (\"Third Party Content\"). The Third Party Content is, in each case, the copyrighted and/or trademarked work of the creator/licensor. You agree to only display the Third Party Content on your personal computer solely for your personal use. You acknowledge and agree that you have no right to download, cache, reproduce, modify, display (except as set forth in this paragraph), edit, alter or enhance any of the Third Party Content in any manner unless you have permission from the owner of the Third Party Content. LADDERS DISCLAIMS ALL EXPRESS, IMPLIED AND STATUTORY WARRANTIES AND CONDITIONS WITH REGARD TO THIRD PARTY CONTENT, INCLUDING, BUT NOT LIMITED TO, ALL IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT."]
                [:p {:style {:font-family "HelveticaNeue"}} "User Content."]
                [:p "You are responsible for the information, opinions, messages, comments, photos, videos, graphics, sounds and other content or material that you submit, upload, post or otherwise make available on or through the Site and/or the Services (\"User Content\"). You may not upload, post or otherwise make available on the Site any material protected by copyright, trademark, or any other proprietary right without the express permission of the owner of such copyright, trademark or other proprietary right owned by a third party, and the burden of determining whether any material is protected by any such right is on you. You shall be solely liable for any damage resulting from any infringement of copyrights, trademarks, proprietary rights, violation of contract, privacy or publicity rights or any other harm resulting from your User Content. You have full responsibility for your User Content, including its legality, reliability and appropriateness."]
                [:p "Unless otherwise explicitly stated herein or in the "
                 [:a {:href "http://www.theladders.com/theladders-privacy" :target "_blank"} "Privacy Policy"]
                 ", you agree that any User Content submitted, uploaded, posted or otherwise made available by you in connection with your use of the Site, and/or Services is provided on a non-proprietary and non-confidential basis. You hereby grant to Ladders a non-exclusive, perpetual, irrevocable, royalty-free, fully paid-up, worldwide license (including the right to sublicense through multiple tiers) to use, reproduce, process, adapt, publicly perform, publicly display, modify, prepare compilations and derivative works of, publish, transmit and distribute your User Content, or any portion thereof, and to publish, transmit, distribute and sell compilations and derivative works of your User Content, in any form, medium or distribution method now known or hereafter existing, known or developed. Ladders may modify or adapt your User Content in order to transmit, display or distribute them over computer networks and in various media and/or make changes to your User Content as necessary to conform and adapt them to any requirements or limitations of any networks, devices, services or media. Without limiting the foregoing, Ladders may take Opportunities posted by you and post, advertise or promote them on the Site or anywhere else for recruiting purposes.  You agree to pay for all royalties, fees, damages and any other monies owing any person by reason of any User Content posted by you to or through the Site. When you provide User Content you agree that such User Content shall not be in violation of the \"Unauthorized Activities\" paragraph below.  <strong>Those prohibitions do not require Ladders to monitor, police or remove any User Content or other information submitted by you or any other user.</strong>"]
                [:p {:style {:font-family "HelveticaNeue"}} "Unauthorized Activities."]
                [:p "When using the Site and/or the Services, you agree not to:"]
                [:ul {:style {:margin-left "30px"}}
                 [:li "Defame, abuse, harass, stalk, threaten, or otherwise violate the legal rights (such as rights of privacy and publicity) of others."]
                 [:li "Use racially, ethnically, or otherwise offensive language."]
                 [:li "Discuss or incite illegal activity."]
                 [:li "Use explicit/obscene language or solicit/post sexually explicit images (actual or simulated)."]
                 [:li "Post anything that exploits children or minors or that depicts cruelty to animals."]
                 [:li "Post any copyrighted or trademarked materials without the express permission from the owner."]
                 [:li "Use any false or inaccurate information for purposes of registering as a user of the Site."]
                 [:li "Delete or revise any material or other information of any other user or the Site, or otherwise alter the opinions or comments posted by others on the Site."]
                 [:li "Disseminate any unsolicited or unauthorized advertising, promotional materials, 'junk mail', 'spam', 'chain letters', 'pyramid schemes', or any other form of such solicitation."]
                 [:li "Use any robot, spider, scraper or other automated means to access the Site."]
                 [:li "Use the Site, the Services or the Materials for any commercial or pecuniary purpose."]
                 [:li "Use the Site in any manner that is harmful to others."]
                 [:li "Attempt to modify, adapt, translate, decipher, decompile, disassemble or reverse engineer any of the software comprising or in any way making up a part of the Site, the Services, or the Materials."]
                 [:li "Reproduce, duplicate, copy, sell, resell or otherwise exploit for any commercial purposes, any portion of, use of, or access to the Site."]
                 [:li "Remove any copyright, trademark or other proprietary rights notice from the Site or materials originating from the Site."]
                 [:li "Frame or mirror any part of the Site without Ladders' prior written consent."]
                 [:li "Create a database, data store, or any other means of data retrieval by systematically downloading, storing or making available by any means any Site content."]
                 [:li "Use the Site in a manner that intentionally or unintentionally violates any applicable local, state, national or international law, or in a manner that is inappropriate, harmful or offensive."]
                 [:li "Take any action that imposes an unreasonable or disproportionately large load on our infrastructure or may otherwise harm, disrupt or overburden the Site."]
                 ]
                [:p "This list of prohibitions provides examples and is not complete or exclusive. Ladders reserves the right to (a) terminate access to your account, your ability to post to the Site (or use the Services) and (b) refuse, delete or remove any User Content; with or without cause and with or without notice, for any reason or no reason, or for any action that Ladders determines, in its sole discretion, is inappropriate or disruptive to the Site or to any other user of the Site and/or Services. Ladders may report to law enforcement authorities any actions that may be illegal, and any reports it receives of such conduct. When legally required or at Ladders' discretion, Ladders will cooperate with law enforcement agencies in any investigation of alleged illegal activity on the Site or on the Internet."]
                [:p "Unauthorized use of any Materials or Third Party Content contained on the Site may violate certain laws and regulations. You agree to indemnify and hold Ladders and its officers, directors, employees, affiliates, agents, licensors, and business partners harmless from and against any and all costs, damages, liabilities, and expenses (including attorneys' fees and costs of defense) Ladders or any other indemnified party suffers in relation to, arising from, or for the purpose of avoiding, any claim or demand from a third party that your use of the Site or the use of the Site by any person using your user name and/or password (including without limitation, your participation in the posting areas or, your User Content) violates any applicable law or regulation, or the copyrights, trademark rights or other rights of any third party."]
                [:p {:style {:font-family "HelveticaNeue"}} "Proprietary Rights."]
                [:p "Trademarks, names and logos on the Site are the property of their respective owners. Unless otherwise specified in these Terms, all information and screens appearing on the Site, including documents, services, design, text, graphics, logos, images and icons, as well as the arrangement thereof, are the sole property of Ladders. All rights not expressly granted herein are reserved. Except as otherwise required or limited by applicable law, any reproduction, distribution, modification, retransmission, or publication of any copyrighted material is strictly prohibited without the express written consent of the copyright owner or license. Notwithstanding anything contained herein, you agree that Ladders may use your logo for any purpose on the Ladders' Site or in promotional emails."]
                [:p {:style {:font-family "HelveticaNeue"}} "Intellectual Property Infringement."]
                [:p "Ladders respects the intellectual property rights of others, and we ask you to do the same. Ladders may, in appropriate circumstances and at our discretion, terminate service and/or access to the Site for users who infringe the intellectual property rights of others. If you believe that your work is the subject of copyright infringement and/or trademark infringement and appears on our Site, please provide Ladders' designated agent the following information:"]
                [:ul {:style {:margin-left "30px"}}
                 [:li "A physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed."]
                 [:li "Identification of the copyrighted and/or trademarked work claimed to have been infringed, or, if multiple works at a single Site are covered by a single notification, a representative list of such works at that the Site, and the date and time of the commission of the claimed infringement."]
                 [:li "Identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled at the Site, and information reasonably sufficient to permit Ladders to locate the material."]
                 [:li "A description of your interests or rights in or to the work claimed to have been infringed."]
                 [:li "Information reasonably sufficient to permit Ladders to contact you as the complaining party, such as an address, telephone number, and, if available, an electronic mail address at which you may be contacted."]
                 [:li "A statement that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright and/or trademark owner, its agent, or the law."]
                 [:li "A statement that the information in the notification is accurate, and under penalty of perjury, that you are authorized to act on behalf of the owner of an exclusive right that is allegedly infringed."]
                 ]
                [:p "Ladders' agent for notice of claims of copyright or trademark infringement on the Site can be reached as follows:"]
                [:p "Ladders, Inc."
                 [:br]
                 "Vice President of Legal Affairs,"
                 [:br]
                 "55 Water Street, 51st Floor"
                 [:br]
                 "New York, NY, 10041"
                 [:br]
                 "By telephone: (646) 453-1800"
                 [:br]
                 "By facsimile: (914) 462-3738"
                 [:br]
                 "E-mail: "
                 [:a {:href "mailto:ReportInfringement@theladders.com"} "ReportInfringement@theladders.com"]]
                [:p "Please also note that for copyright infringements under Section 512(f) of the Copyright Act (US), any person who knowingly materially misrepresents that material or activity is infringing may be subject to liability."]
                [:p {:style {:font-family "HelveticaNeue"}} "Indemnification"]
                [:p "You agree to defend, indemnify and hold harmless Ladders from any claim or demand including reasonable attorney's fees and costs, made by any third party arising out of or related to (i) your use of the Site in violation of these Terms; (ii) your User Content; (iii) your infringement of the intellectual property rights of another; or (iv) your violation of any state or federal law or regulation in connection with your use of the Services. Ladders reserves the right and shall have the option, at its own expense to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, and in such case, you agree to cooperate with Ladders' defense of such claim."]
                [:p {:style {:font-family "HelveticaNeue"}} "Submitting a DMCA Counter-Notification"]
                [:p "Upon receiving a notice of claimed infringement that complies with the requirements set out above, and upon payment of any fee that we may lawfully charge, we will forward the notice to the location you have provided (or, if we are unable to forward it, we will inform you of the reasons)."]
                [:p "We also reserve the right to remove or disable access to copyright-protected material that you provided, if such removal is pursuant to a valid infringement notice that we have received. If you receive such notice from us, you may provide us with a counter-notification in writing to Ladders designated agent that includes all of the following information:"]
                [:ul {:style {:margin-left "30px"}}
                 [:li "Your physical or electronic signature;"]
                 [:li "Identification of the material that has been removed or to which access has been disabled, and the location at which the material appeared before it was removed or access to it was disabled;"]
                 [:li "A statement from you under the penalty of perjury, that you have a good faith belief that the material was removed or disabled as a result of a mistake or misidentification of the material to be removed or disabled; and"]
                 [:li "Your name, physical address and telephone number, and a statement that you consent to the jurisdiction of a court for the judicial district in which your physical address is located, or if your physical address is outside of the United States, for any judicial district in which Ladders may be located, and that you will accept service of process from the person who provided notification of allegedly infringing material or an agent of such person."]
                 ]
                [:p {:style {:font-family "HelveticaNeue"}} "Termination of Repeat Infringers."]
                [:p "Ladders reserves the right, in its sole discretion, to terminate the account or access of any user of our Site and/or Service who is the subject of repeated DMCA or other infringement notifications."]
                [:p {:style {:font-family "HelveticaNeue"}} "Disclaimer of Warranties."]
                [:p "Your use of the Site and/or the Services is at your own risk. The Materials have not been verified or authenticated in whole or in part by Ladders, and they may include inaccuracies or typographical or other errors. Ladders does not warrant the accuracy of timeliness of the Materials contained on the Site. Ladders has no liability for any errors or omissions in the Materials, whether provided by Ladders, our licensors or suppliers or other users."]
                [:p "THE LAWS OF CERTAIN JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LEGAL WARRANTIES AND THE EXCLUSION OR LIMITATION OF REPRESENTATIONS MADE CONCERNING GOODS OR SERVICES.  IF THESE LAWS APPLY TO YOU, SOME OR ALL OF THE BELOW EXCLUSIONS OR LIMITATIONS MAY NOT APPLY TO YOU."]
                [:p "LADDERS, FOR ITSELF AND ITS LICENSORS, MAKES NO EXPRESS, IMPLIED OR STATUTORY REPRESENTATIONS, WARRANTIES, OR GUARANTEES IN CONNECTION WITH THE SITE, THE SERVICES, OR ANY MATERIALS, RELATING TO THE QUALITY, SUITABILITY, TRUTH, ACCURACY OR COMPLETENESS OF ANY INFORMATION OR MATERIAL CONTAINED OR PRESENTED ON THE SITE, INCLUDING WITHOUT LIMITATION THE MATERIALS, ANY USER CONTENT AND ANY THIRD PARTY CONTENT. UNLESS OTHERWISE EXPLICITLY STATED, TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE SITE, THE SERVICES, AND MATERIALS, AND ANY INFORMATION CONTAINED OR PRESENTED ON THE SITE IS PROVIDED TO YOU ON AN \"AS IS,\" \"AS AVAILABLE\" AND \"WHERE-IS\" BASIS WITH NO WARRANTY OF IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT OF THIRD PARTY RIGHTS. LADDERS DOES NOT PROVIDE ANY WARRANTIES AGAINST VIRUSES, SPYWARE OR MALWARE THAT MAY BE INSTALLED ON YOUR COMPUTER."]
                [:p {:style {:font-family "HelveticaNeue"}} "Limitation of Liability."]
                [:p "Ladders provides a venue for employers/recruiters to post jobs and search for candidates, and for candidates to post resumes and search for jobs. Ladders is not involved in the actual transaction between employers/recruiters and candidates. As a result, Ladders has no control over User Content, or the quality, safety, or legality of jobs or resumes posted and makes no representations about any jobs, resumes or User Content. Ladders shall not be responsible for any employment decisions, for whatever reason, made by any entity in connection with jobs posted on or through the Site. You acknowledge and agree that you are solely responsible for the accuracy, form and substance of any of your User Content. You further acknowledge and agree that you are responsible for evaluating any Materials (including but not limited to job postings) and that Ladders shall not be responsible for your career decisions."]
                [:p "THE LAWS OF CERTAIN JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY, OR OF CERTAIN DAMAGES. IF THESE LAWS APPLY TO YOU, SOME OR ALL OF THE BELOW EXCLUSIONS OR LIMITATIONS MAY NOT APPLY TO YOU, AND YOU MAY HAVE ADDITIONAL RIGHTS."]
                [:p "LADDERS SHALL NOT BE LIABLE TO YOU FOR ANY DAMAGES RESULTING FROM YOUR DISPLAYING, COPYING, OR DOWNLOADING ANY MATERIALS TO OR FROM THE SITE. IN NO EVENT SHALL LADDERS BE LIABLE TO YOU FOR ANY INDIRECT, EXTRAORDINARY, EXEMPLARY, PUNITIVE, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES (INCLUDING LOSS OF DATA, REVENUE, PROFITS, USE OR OTHER ECONOMIC ADVANTAGE) HOWEVER ARISING, EVEN IF LADDERS KNOWS THERE IS A POSSIBILITY OF SUCH DAMAGE."]
                [:p "LADDERS' MAXIMUM TOTAL, AGGREGATE LIABILITY ARISING OUT OF OR IN CONNECTION WITH THE SITE AND ANY MATERIALS OR SERVICES PROVIDED THEREIN, REGARDLESS OF THE CAUSE OF ACTION (WHETHER IN CONTRACT, TORT, BREACH OF WARRANTY OR OTHERWISE), WILL IN NO EVENT EXCEED THE TOTAL AMOUNT YOU HAVE PAID TO LADDERS WITHIN THE TWELVE (12) MONTH PERIOD PRECEDING THE DATE THE CLAIM FIRST AROSE."]
                [:p {:style {:font-family "HelveticaNeue"}} "Local Laws; Export Control."]
                [:p "Ladders controls and operates the Site from its headquarters in the United States of America, and the Materials may not be appropriate or available for use in other locations. If you use the Site outside the United States of America and Canada, you are responsible for following applicable local laws."]
                [:p {:style {:font-family "HelveticaNeue"}} "Feedback."]
                [:p "If you send or transmit any communications, comments, questions, suggestions, or related materials to Ladders, whether by letter, email, telephone, or otherwise (collectively, \"Feedback\"), suggesting or recommending changes to the Site, any Services or Materials, including, without limitation, new features or functionality relating thereto, all such Feedback is, and will be treated as, non-confidential and non-proprietary. You hereby assign all right, title, and interest in, and Ladders is free to use, without any attribution or compensation to you, any ideas, know-how, concepts, techniques, or other intellectual property and proprietary rights contained in the Feedback, whether or not patentable, for any purpose whatsoever, including but not limited to, developing, manufacturing, having manufactured, licensing, marketing, and selling, directly or indirectly, products and services using such Feedback. You understand and agree that Ladders is not obligated to use, display, reproduce, or distribute any such ideas, know-how, concepts, or techniques contained in the Feedback, and you have no right to compel such use, display, reproduction, or distribution."]
                [:p {:style {:font-family "HelveticaNeue"}} "Dispute Resolution and Arbitration; Class Action Waiver."]
                [:p {:style {:font-family "HelveticaNeue"}} "Please read this carefully. It affects your rights."]
                [:p "Most user concerns can be resolved quickly and to a user's satisfaction by contacting us at <a href=\"mailto:rrsupport@theladders.com\">rrsupport@theladders.com</a>. This Provision facilitates the prompt and efficient resolution of any disputes that may arise between you and Ladders. Arbitration is a form of private dispute resolution in which persons with a dispute waive their rights to file a lawsuit, to proceed in court and to a jury trial, and instead submit their disputes to a neutral third person (or arbitrator) for a binding decision. You have the right to opt-out of this Provision (as explained below), which means you would retain your right to litigate your disputes in a court, either before a judge or jury."]
                [:p "Please read this Provision carefully. It provides that , except where prohibited by applicable law, all Disputes between you and Ladders shall be resolved by binding arbitration. Arbitration replaces the right to go to court. In the absence of this arbitration agreement, you may otherwise have a right or opportunity to bring claims in a court, before a judge or jury, and/or to participate in or be represented in a case filed in court by others (including, but not limited to, class actions). Except as otherwise provided, entering into this agreement constitutes a waiver of your right to litigate claims and all opportunity to be heard by a judge or jury. There is no judge or jury in arbitration, and court review of an arbitration award is limited. The arbitrator must follow this agreement and can award the same damages and relief as a court (including attorney's fees)."]
                [:p "For the purpose of this Provision, \"Ladders\" means Ladders and its parents, subsidiary, and affiliate companies, and each of their respective officers, directors, employees, and agents. The term \"Dispute\" means any dispute, claim, or controversy between you and Ladders regarding , arising out of or relating to any aspect of your relationship with Ladders, whether based in contract, statute, regulation, ordinance, tort (including, but not limited to, fraud, misrepresentation, fraudulent inducement, or negligence), or any other legal or equitable cause of action or claim for relief, and includes the validity, enforceability or scope of this Provision (with the exception of the enforceability of the Class Action Waiver clause below). \"Dispute\" is to be given the broadest possible meaning that will be enforced, and shall include any claims against other parties relating to services or products provided or billed to you (such as Ladders' licensors, suppliers, dealers or third party vendors) whenever you also assert claims against us in the same proceeding."]
                [:p "WE EACH AGREE THAT, EXCEPT AS PROVIDED BELOW OR WHERE PROHIBITED BY APPLICABLE LAW, ANY AND ALL DISPUTES, AS DEFINED ABOVE, WHETHER PRESENTLY IN EXISTENCE OR BASED ON ACTS OR OMISSIONS IN THE PAST OR IN THE FUTURE, WILL BE RESOLVED EXCLUSIVELY AND FINALLY BY BINDING ARBITRATION RATHER THAN IN COURT IN ACCORDANCE WITH THIS PROVISION."]
                [:p "Pre-Arbitration Claim Resolution"]
                [:p "For all Disputes, whether pursued in court or arbitration, you must first give Ladders an opportunity to resolve the Dispute. You must commence this process by mailing written notification to:"]
                [:p "Ladders, Inc."
                 [:br]
                 "Vice President of Legal Affairs,"
                 [:br]
                 "55 Water Street, 51st Floor"
                 [:br]
                 "New York, NY, 10041"]
                [:p "That written notification must include (1) your name, (2) your address, (3) a written description of your Claim, and (4) a description of the specific relief you seek. If Ladders does not resolve the Dispute within 45 days after it receives your written notification, you may pursue your Dispute in arbitration or, only where arbitration is prohibited by law, in court. You may pursue your Dispute in a court only under the circumstances described below."]
                [:p "Exclusions from Arbitration; Right to Opt Out"]
                [:p "Notwithstanding the above, you or Ladders may choose to pursue a Dispute in court and not by arbitration if (a) the Dispute qualifies, it may be initiated in small claims court; or (b) YOU OPT-OUT OF THESE ARBITRATION PROCEDURES WITHIN 30 DAYS FROM THE DATE THAT YOU FIRST CONSENT TO THIS AGREEMENT (the \"Opt-Out Deadline\"). You may opt out of this Provision by mailing written notification to Ladders, disputeresolution@theladders.com. Your written notification must include (1) your name, (2) your address, and (3) a clear statement that you do not wish to resolve disputes with Ladders through arbitration. Your decision to opt-out of this Arbitration Provision will have no adverse effect on your relationship with Ladders.  Any opt-out request received after the Opt-Out Deadline will not be valid and you must pursue your Dispute in arbitration or small claims court."
                 [:span {:style {:font-family "HelveticaNeue"}} " Any opt-out request received after the Opt-Out Deadline will not be valid and you must pursue your Dispute in arbitration or small claims court."]]
                [:p "Arbitration Procedures"]
                [:p "If this Provision applies and the Dispute is not resolved as provided above (Pre-Arbitration Claim Resolution) either you or Ladders may initiate arbitration proceedings. The American Arbitration Association (\"AAA\"), www.adr.org, or JAMS, www.jamsadr.com, will arbitrate all Disputes, and the arbitration will be conducted before a single arbitrator. The arbitration shall be commenced as an individual arbitration only, and shall in no event be commenced as a class arbitration or a consolidated or representative action or arbitration. All issues shall be for the arbitrator to decide, including the scope of this Provision."]
                [:p "For arbitration before AAA, for Disputes of less than $75,000, the AAA's Supplementary Procedures for Consumer-Related Disputes will apply; for Disputes involving $75,000 or more, the AAA's Commercial Arbitration Rules will apply. In either instance, the AAA's Optional Rules For Emergency Measures Of Protection shall apply. The AAA rules are available at www.adr.org or by calling 1-800-778-7879. For arbitration before JAMS, the JAMS Comprehensive Arbitration Rules & Procedures and the JAMS Recommended Arbitration Discovery Protocols For Domestic, Commercial Cases will apply. The JAMS rules are available at www.jamsadr.com or by calling 1-800-352-5267. This Provision governs in the event it conflicts with the applicable arbitration rules. Under no circumstances will class action or representative action procedures or rules apply to the arbitration."]
                [:p "Because the Site and these Terms concern interstate commerce, the Federal Arbitration Act (\"FAA\") governs the arbitrability of all Disputes. However, the arbitrator will apply applicable substantive law consistent with the FAA and the applicable statute of limitations or condition precedent to suit."]
                [:p "Arbitration Award -- The arbitrator may award on an individual basis any relief that would be available pursuant to applicable law, and will not have the power to award relief to, against or for the benefit of any person who is not a party to the proceeding. The arbitrator will make any award in writing but need not provide a statement of reasons unless requested by a party or if required by applicable law. Such award will be final and binding on the parties, except for any right of appeal provided by the FAA or other applicable law, and may be entered in any court having jurisdiction over the parties for purposes of enforcement."]
                [:p "Location of Arbitration -- you or Ladders may initiate arbitration in either New York County, New York or, if you reside in the United States, the federal judicial district that includes your billing address."]
                [:p "Payment of Arbitration Fees and Costs -- Ladders will pay all arbitration filing fees and AAA or JAMS hearing fees and any arbitrator's hearing fees, costs and expenses upon your written request to the arbitrator given at or before the first evidentiary hearing in the arbitration. You are responsible for all additional fees and costs that you incur in the arbitration, including, but not limited to, attorneys or expert witnesses. Fees and costs may be awarded as provided pursuant to applicable law. In addition to any rights to recover fees and costs under applicable law, if you provide notice and negotiate in good faith with Ladders as provided in the section above titled \"Pre-Arbitration Claim Resolution\" and the arbitrator concludes that you are the prevailing party in the arbitration, you will be entitled to recover reasonable attorney's fees and costs as determined by the arbitrator."]
                [:p "Class Action Waiver"]
                [:p "Except as otherwise provided in this Provision or by applicable law, the arbitrator may not consolidate more than one person's claims, and may not otherwise preside over any form of a class or representative proceeding or claims (such as a class action, consolidated action, representative action, or private attorney general action) unless both you and Ladders specifically agree to do so in writing following initiation of the arbitration."
                 [:span {:style {:font-family "HelveticaNeue"}} " If you choose to pursue your Dispute in court by opting out of the Arbitration Provision, as specified above, this Class Action Waiver will not apply to you. Neither you"]
                 ", nor any other user of the Site can be a class representative, class member, or otherwise participate in a class, consolidated, or representative proceeding without having complied with the opt-out requirements above."]
                [:p "Severability"]
                [:p "If any clause within this Provision (other than the Class Action Waiver clause above) is found to be illegal or unenforceable, that clause will be severed from this Provision, and the remainder of this Provision will be given full force and effect. If the Class Action Waiver clause is found to be illegal or unenforceable, this entire Provision will be unenforceable and the Dispute will be decided by a court."]
                [:p "Continuation"]
                [:p "This Provision shall survive the termination of your service with Ladders or its affiliates. Notwithstanding any provision in this Agreement to the contrary, we agree that if Ladders makes any change to this Provision (other than a change to the Notice Address), you may reject any such change and require Ladders to adhere to the present language in this Provision if a dispute between us arises."]
                [:p {:style {:font-family "HelveticaNeue"}} "Termination."]
                [:p "Ladders may discontinue, suspend or terminate your access to the Site, the Services and/or your account, without notice or liability for any violation of these Terms or for any other use of the Site, the Services or the Materials that Ladders, at its sole discretion, deems improper. Ladders may also discontinue offering the Site, the Materials or any of the Services, or may modify any portion of the Site, the Materials or the Services at any time with or without notice to you."]
                [:p {:style {:font-family "HelveticaNeue"}} "Violations."]
                [:p "Ladders prefers to advise you if we feel you are not complying with these Terms and to recommend any necessary corrective action. However, certain violations of these Terms, as determined by Ladders, may result in immediate termination of your access to the Site without prior notice to you."]
                [:p {:style {:font-family "HelveticaNeue"}} "Choice of Law and Venue."]
                [:p "Subject to applicable consumer protection laws, the Federal Arbitration Act, New York state law and applicable U.S. federal law, without regard to choice of law or conflicts of law provisions, will govern these Terms. Foreign laws do not apply. The United Nations Convention on Contracts for the International Sale of Goods and any laws based on the Uniform Computer Information Transactions Act (UCITA) shall not apply to this Agreement. Except for Disputes subject to arbitration as described above, or where otherwise prohibited by law, any disputes relating to these Terms or the Site will be heard in the courts located in New York County in the State of New York."]
                [:p {:style {:font-family "HelveticaNeue"}} "Language."]
                [:p "The Parties hereto have expressly required that this agreement and all documents and notices relating thereto be drafted in the English language."
                 [:em "Les parties aux pr"(gstring/unescapeEntities "&eacute;")"sentes ont express"(gstring/unescapeEntities "&eacute;")"ment exig"(gstring/unescapeEntities "&eacute;")" que la pr"(gstring/unescapeEntities "&eacute;")"sente convention et tous les autres documents ou avis qui y sont aff"(gstring/unescapeEntities "&eacute;")"rents soient r"(gstring/unescapeEntities "&eacute;")"dig"(gstring/unescapeEntities "&eacute;")"s en langue anglais."] ]
                [:p {:style {:font-family "HelveticaNeue"}} "General."]
                [:p "With the exception of the \"Severability\" paragraph of the \"Dispute Resolution and Arbitration; Class Action Waiver\" agreement above, if any provision of these Terms is found to be invalid by any court having competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of these Terms of Use, which shall remain in full force and effect. Ladders' failure to enforce any term of these Terms shall not be deemed as a waiver of such term or otherwise affect Ladders' ability to enforce such term at any point in the future.  These Terms are the entire agreement between you and Ladders and supersede all prior or contemporaneous negotiations, discussions or agreements between you and Ladders about the Site.  The proprietary rights, disclaimer of warranties, representations made by you, indemnities, limitations of liability and general provisions shall survive any termination of these Terms."]
                [:p {:style {:font-family "HelveticaNeue"}} "Contact Us"]
                [:p "If you have any questions about these Terms or otherwise need to contact Ladders for any reason, you can reach us at "
                 [:a {:href "mailto:rrsupport@theladders.com"} "rrsupport@theladders.com"]]
                ]]))

(defn body
  []
  (fn []
    [rc/h-box
     :class "content-holder"
     :children [
                [rc/v-box
                 :class "content"
                 :children [[title] [paras]]]]]))

(defn index
  []
  (fn []
    [rc/h-box
     :class "terms-and-conditions faqs main"
     :children [[body]]]))